services:

  document-flow:
    build: ./
    image: document-flow:1.0
    container_name: document-flow
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - document-flow-db
      - minio
    environment:
      - DB_NAME=document-flow
      - USER=root
      - PASSWORD=root
      - DB_HOST=document-flow-db
      - DB_PORT=5432
      - JAVA_TOOL_OPTIONS= "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - docflow_1.0

  document-flow-db:
    image: postgres:16-alpine
    container_name: document-flow-db
    environment:
      - POSTGRES_DB=docflow
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - docflow_1.0
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Secure123$$
    networks:
      - docflow_1.0

networks:
  docflow_1.0:
    driver: bridge