services:

  document-flow:
    build: ./
    image: document-flow:1.0
    container_name: document-flow
    ports:
      - "8080:8080"
    depends_on:
      - document-flow-db
      - minio
      - kafka
    command: "--kafka.bootstrap_servers=kafka:9092"
    environment:
      - DB_NAME=docflow
      - USER=root
      - PASSWORD=root
      - DB_HOST=document-flow-db
      - DB_PORT=5432
      - EMAIL=mailingervice@example.com
      - MAIL_PASSWORD=mailingServicePassword
    networks:
      - minio
      - database
      - kafka
    profiles:
      - ""

  document-flow-db:
    image: postgres:16-alpine
    container_name: document-flow-db
    environment:
      - POSTGRES_DB=docflow
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - database
    profiles:
      - ""

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Secure123$$
    networks:
      - minio
    profiles:
      - ""

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    networks:
      - kafka
    profiles:
      - ""

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka
    profiles:
      - ""

  document-flow-test:
    build: ./
    image: document-flow
    container_name: document-flow-test
    healthcheck:
      test:  curl --fail http://127.0.0.1:8080/swagger-ui/index.html || exit 1
      interval: 3s
      timeout: 2s
      retries: 90
    depends_on:
      - document-flow-db-test
      - minio-test
      - kafka-test
    command: "--kafka.bootstrap_servers=kafka-test:9092 --spring.profiles.active=dev,test"
    environment:
      - DB_NAME=document-flow-test
      - USER=root
      - PASSWORD=root
      - DB_HOST=document-flow-db-test
      - DB_PORT=5432
      - EMAIL=mailingervice@example.com
      - MAIL_PASSWORD=mailingServicePassword
    networks:
      - test
    profiles:
      - "test"

  document-flow-db-test:
    image: postgres:16-alpine
    container_name: document-flow-db-test
    environment:
      - POSTGRES_DB=document-flow-test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - test
    profiles:
      - "test"

  minio-test:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Secure123$$
    networks:
      - test
    profiles:
      - "test"

  zookeeper-test:
    image: zookeeper:3.7.0
    container_name: zookeeper-test
    networks:
      - test
    profiles:
      - "test"

  kafka-test:
    image: obsidiandynamics/kafka
    container_name: kafka-test
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka-test:29092,DOCKER_EXTERNAL://kafka-test:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper-test
    networks:
      - test
    profiles:
      - "test"

  document-flow-e2e-test:
    build: ./E2E-Integration-Test
    image: document-flow-e2e-test
    container_name: document-flow-e2e-test
    environment:
      - TARGET_URL=http://document-flow-test:8080
    depends_on:
        document-flow-test:
            condition: service_healthy
    networks:
      - test
    profiles:
      - "test"


networks:
  minio:
    driver: bridge
  database:
    driver: bridge
  kafka:
    driver: bridge
  test:
    driver: bridge




