services:

  document-flow:
    build: ./
    image: document-flow
    container_name: document-flow
    ports:
      - "8080:8080"
    depends_on:
      - document-flow-db
    environment:
      - DB_NAME=document-flow
      - USER=root
      - PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  document-flow-db:
    image: postgres:14-alpine
    container_name: document-flow-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=document-flow
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root